image: node:6
clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - yarn
          - yarn global add gulp gulp-cli
          - gulp production
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD